<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QJHRQ4H" ignored="0" name="Test" tests="28" failures="3" timestamp="2023-03-20T23:04:53 MSK" time="0.503" errors="0">
  <testcase name="test2" time="0.077" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test_name" time="0.093" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test2" time="0.075" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test3" time="0.072" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test1" time="0.075" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test1" time="0.071" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test2" time="0.074" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test3" time="0.078" classname="online_tusur.unit_online_tusur.StudTestNG">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;50&amp;gt; but was:&amp;lt;18&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<50> but was:<18>
at online_tusur.unit_online_tusur.StudTestNG.test3(StudTestNG.java:61)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test_AVG" time="0.082" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test2" time="0.075" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test3" time="0.076" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test_MIN" time="0.081" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test3" time="0.077" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test1" time="0.069" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test1" time="0.068" classname="online_tusur.unit_online_tusur.StudTestNG">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;K&amp;gt; but was:&amp;lt;k&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<K> but was:<k>
at online_tusur.unit_online_tusur.StudTestNG.test1(StudTestNG.java:36)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test_MAX" time="0.079" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <testcase name="test4" time="0.012" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test4" time="0.002" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test4" time="0.004" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test4" time="0.003" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test5" time="0.026" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test6" time="0.002" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test5" time="0.003" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test6" time="0.001" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test5" time="0.003" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test6" time="0.005" classname="online_tusur.unit_online_tusur.TestStudent">
    <failure type="java.lang.AssertionError" message="expected [18] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at online_tusur.unit_online_tusur.TestStudent.test6(StudentTestFactory.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase name="test5" time="0.002" classname="online_tusur.unit_online_tusur.TestStudent"/>
  <testcase name="test6" time="0.002" classname="online_tusur.unit_online_tusur.TestStudent"/>
</testsuite> <!-- Test -->
